# Project: Project1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o ../../../../TATU/dasturlash/2.2.c.o wwwwwwwwwwww.o
LINKOBJ  = main.o ../../../../TATU/dasturlash/2.2.c.o wwwwwwwwwwww.o
LIBS     = -L"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/JamshidbekAxlidinov/embercadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\JamshidbekAxlidinov\embercadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

../../../../TATU/dasturlash/2.2.c.o: ../../../../TATU/dasturlash/2.2.c.cpp
	$(CPP) -c ../../../../TATU/dasturlash/2.2.c.cpp -o ../../../../TATU/dasturlash/2.2.c.o $(CXXFLAGS)

wwwwwwwwwwww.o: wwwwwwwwwwww.cpp
	$(CPP) -c wwwwwwwwwwww.cpp -o wwwwwwwwwwww.o $(CXXFLAGS)
